name: K8s Cluster Audit

on:
  push:
    branches: [ "main" ]

jobs:
  k8s-check:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List Cluster Nodes
        run: |
          echo "Verificando nós do cluster..."
          kubectl get nodes -o wide
          
      - name: Check Resource Usage
        run: |
          echo "Uso de recursos no namespace default:"
          kubectl top pods || echo "Metrics Server não instalado"
